-- Create users table
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cordinates(
    id SERIAL PRIMARY KEY,
    LAT VARCHAR(6) NOT NULL,
    LON VARCHAR(6) NOT NULL,
    DT_UPLOAD DATETIME
)

-- Grant privileges on users table to lynch_admin
GRANT ALL PRIVILEGES ON TABLE users TO lynch_admin;
GRANT USAGE, SELECT ON SEQUENCE users_id_seq TO lynch_admin; 